### ISSUE TITLE
console errors

### ISSUE THREAD

**Issue by ahmetozalp** [troybetz/react-youtube#114]
http://oi66.tinypic.com/29gdggi.jpg

**Comment by tjallingt** [comment]
I'm sorry you are experiencing an issue while using react-youtube but I'd like to point out that from just these errors no-one will be able to help you. If you want our help with your problem then please give us more information about what you are trying to do and what is not working if possible using code that demonstrates where the problem lies.

Additionally: spamming a seemingly unrelated issue with a stack traces of errors that you are experiencing does not help either.
