### ISSUE TITLE
Youtube thumbnail size

### ISSUE THREAD

**Issue by Oskarino29** [troybetz/react-youtube#115]
Hello - is it possible to target the thumbnail of the YouTube video so that I can edit the background-size (+ browser-specific variants)? I would like to set it to `contain` so that it is consistent with the video within a container with responsive width. Thanks, loving the plugin!

**Comment by goto-bus-stop** [comment]
Hi! By the thumbnail, do you mean the one that's shown before the video starts? It's inside an iframe, so you can't target it with CSS unfortunately.

**Comment by tjallingt** [comment]
Hello @Oskarino29, this library does not have any functionality regarding YouTube's thumbnails...
If you want to overlay a thumbnail over your video before it is played you'll have to request the video thumbnail using the YouTube Data API and display that instead of the video element until it is "activated".
Hope this helps.

**Comment by Oskarino29** [comment]
Thanks @tjallingt I will give that a try!
