### ISSUE TITLE
Playlist

### ISSUE THREAD

**Issue by kamalkech** [troybetz/react-youtube#126]
In documentation i can't found playlist implementation ?!!

**Comment by tjallingt** [comment]
Please read the first line of the [readme](https://github.com/troybetz/react-youtube/blob/master/README.md) file:

> Simple React component acting as a thin layer over the [YouTube IFrame Player API](https://developers.google.com/youtube/iframe_api_reference)

We don't provide any kind of playlist implementation in this package, you'll have to use the youtube iframe player api in order to implement such functionality.

in response to: https://github.com/troybetz/react-youtube/issues/127

> @kamalkech:
> # Stupide package
> Any thing works with this module, lost my time here.

If you are asking for help from people who offer their time to provide you with opensource code atleast be a little bit respectful

**Comment by kamalkech** [comment]
@tjallingt : sorry because i was angry, but still not working
i already read documentation and i follow instruction of implementation 100% and i get this error : 
'Youtube' is not defined  react/jsx-no-undef

and if i import Youtube i get : Unused import YouTube from 'react-youtube'

**Comment by tjallingt** [comment]
`YouTube`/`Youtube` please check your capitalization.
