### ISSUE TITLE
Dont preload video

### ISSUE THREAD

**Issue by Chaoste** [troybetz/react-youtube#133]
Hi there,

i want to create a page with multiple videos and the browser can't handle the webpage - so it crashes. I would like to like add "preload:none" to the video tag and load it on an hovering event.

Great example: https://codepen.io/gil--/pen/bNxZWg

Greetings,
Thomas

**Comment by tjallingt** [comment]
This functionality isn't offered by the youtube iframe api and since this project aims to be a minimal wrapper i don't think we will implement it.
I'd recommend you create your own VideoPlayer element wrapping `react-youtube` which uses the video id to load a thumbnail and display that until you actually want to load the video.

**Comment by Chaoste** [comment]
Hi tjallingt,

thanks for the answer. I already built a wrapper based on your package. If people are interested in it I might publish it :)

Greetings,
Thomas
