### ISSUE TITLE
Youtube iframe container should be a <div> instead of a <span>

### ISSUE THREAD

**Issue by YPCrumble** [troybetz/react-youtube#151]
Thanks for this simple library! Very quick to implement and saved me a ton of time :). 

I'm trying to style my video embed player and finding that the `<span>` element means that I can't set widths like I want to using the `containerClassName` prop. Is there a reason that the component is wrapped in a `<span>` vs. being wrapped in a `<div>` element? Happy to submit a PR to make the change if that makes sense and is helpful.

**Comment by tjallingt** [comment]
Initially we did not offer a containerClassName prop and wrapped the youtube player with a span. Because of the default behaviour of the span it is possible to just apply styles to the player directly and not have to worry about the span being there.

containerClassName was mostly added for those rare cases where one does have to style the span element to achieve a certain behaviour.

Since the span is meant as a non-obtrusive wrapper I'd like to keep it that way. If you want to give the player a width you should apply that directly to the player. If you really have to give the width to the span apply `display: inline-block`...

PS
the reason for having a wrapper in the first place is so that react can have an element to remove during unmounting. Without a wrapper the modifications by the youtube iframe api make React loose track of the dom element.
