### ISSUE TITLE
How to set an iframe's width to 100% of its parent <div> ?

### ISSUE THREAD

**Issue by nakamotoo** [troybetz/react-youtube#161]
I want to set my iframe width to 100% , my code is like this:

`const opts = {width: '100%'};`
`return(`
`<div  style={{width: '1000px'}}>`
    `<YouTube videoId="2g811Eo7K8U" opts={opts} />`
`</div>`

but there is a span tag between div tag and iframe tag  by default ,
and the width of span tag is 300px.
Is there any solution to control the width of span tag and set the width of <iframe> to 100% ?

**Comment by tjallingt** [comment]
There should be no problem applying css to the iframe in order to give it a 100% width.
Default styling on spans doesn't set a width on them so you should probably look into whatever is causing all your spans to be 300px wide. This really shouldn't be necessary but you can apply styling to the span using the `containerClassName` prop.

https://github.com/tjallingt/react-tjube/blob/master/src/components/Player/Player.jsx

https://github.com/tjallingt/react-tjube/blob/master/src/components/VideoAppPlayer.css#L6-L7

**Comment by nakamotoo** [comment]
Finally it works !  
The reason why it did't work well was that I set `display: flex` to the parent div.
Thanks a lot !!
