### ISSUE TITLE
When URL changes why destroy player vs keep using existing player and loadVideoById?

### ISSUE THREAD

**Issue by paulwehner** [troybetz/react-youtube#26]
Hey, I was just wondering why with the url prop changing you choose to destroy the player and create a new one versus keep the existing player and load the new video using the loadVideoById method? I would imagine loadVideoById would be quicker, and if the video is fullscreen, it wouldn't reset the view.

**Comment by compedit** [comment]
There were a few pain points combining `loadVideoById`, and the [player parameters](https://developers.google.com/youtube/player_parameters) passed into the component. `loadVideoById` sucks and completely ignores the `autoplay` parameter, so that param would have to be tracked internally, and at the time I took it out I was trying to match API compat with the regular iframe API

I'm not against trying to reintegrate it though, would definitely review any PRs for it!
