### ISSUE TITLE
 (0 , _sister2.default) is not a function

### ISSUE THREAD

**Issue by KeweiCodes** [troybetz/react-youtube#56]
I'm using webpack and ES6 classes, and getting this error after recently updating react-youtube.

**Uncaught TypeError: (0 , _sister2.default) is not a function**

Any ideas why this might happen?

**Comment by tjallingt** [comment]
Strange, at first glance I think it might be an issue with your webpack setup but i'm not quite sure...
It seems that webpack can't consolidate the `module.exports` from the [sister](https://github.com/gajus/sister/) library that is used by `youtube-player` a youtube api abstraction that `react-youtube` uses.

Perhaps if you supply some more information (such as webpack.config etc) I could get a better idea...

**Comment by antongorodezkiy** [comment]
I have the same issue. Not sure why, but type of `_sister` variable 
```
var _sister = require('sister');
```
is an object instead of function.

I believe this is not the issue of your package but the issue of `sister` package. I removed 6-7, 68-69 and 73-74 lines https://github.com/gajus/sister/blob/master/dist/sister.js and after that the error disappears.
