### ISSUE TITLE
Iframe loading inconsistently 

### ISSUE THREAD

**Issue by PhilipBrady13** [troybetz/react-youtube#68]
Been experiencing inconsistent loading of the iframe in Chrome, Safari, and FF. There are no errors when it doesn't load, and no indicators in the network panel. Other times it loads perfectly fine. Anyone experiencing this?

**Comment by tjallingt** [comment]
Which version of `react-youtube` do you use? (did you try if your problem still occurs with the latest version?)
Can you share your code for rendering the `react-youtube` component?
With these details we could perhaps help you further...

**Comment by PhilipBrady13** [comment]
5.1.0, i think it was just an issue loading the youtube api asynchronously i assume on my end. ended up writing my own component that works, so will close this now.

**Comment by passrafi** [comment]
I'm having the similar issue @PhilipBrady13 that produces the same symptoms. 
Just to clarify the iframe that fails is an external iframe not related to youtube?
The iframe fails to load with no errors or indicators in the network panel.

**Comment by kahjav** [comment]
I am having the same experience. If I refresh the page 2 times consecutively, it appears. 

Version 6.1.0

**Comment by tjallingt** [comment]
Excuse me for the slow response.
Can you confirm that this issue is also happening when you run the example included with

**Comment by kahjav** [comment]
When it does not load, there is a `div` instead of an `iframe`

**Comment by PhilipBrady13** [comment]
i was getting a div instead of an iframe when the youtube api was not loading in time for render.

**Comment by tjallingt** [comment]
> @kahjav 
Example worked swimmingly!

That would suggest that there is something specific about your application that makes it stop working when you refresh the browser, correct?
The usage of the component doesn't look out of the ordinary so then I'd have to assume there is a bug in the building process that is causing this error.

> @kahjav 
When it does not load, there is a `div` instead of an `iframe`

> @PhilipBrady13 
i was getting a div instead of an iframe when the youtube api was not loading in time for render.

This suggests that the YouTube Iframe API doesn't get loaded and/or instantiated by `react-youtube`.
A few things that I'd like to know:
- is there a script in the `<head>` of your page with `src="https://www.youtube.com/iframe_api"`?
- is there is a global `YT` variable?
(open chrome devtools console and type `YT` it should respond with `Object {loading: 1, loaded: 1, PlayerState: Object, UploadWidgetEvent: Object, UploadWidgetState: Object}`)
- do the `onReady` or `onError` events trigger?

@PhilipBrady13, do you happen to use any of the same packages as @kahjav (specifically from devDependencies)?

**Comment by PhilipBrady13** [comment]
i am using most of them actually, although earlier versions. heres my devDependencies:

"devDependencies": {
    "autoprefixer": "^6.3.1",
    "autoprefixer-loader": "^3.2.0",
    "babel-core": "6.3.26",
    "babel-eslint": "^4.1.3",
    "babel-loader": "^6.2.0",
    "babel-plugin-react-transform": "^2.0.0-beta1",
    "babel-plugin-syntax-class-properties": "^6.3.13",
    "babel-plugin-syntax-decorators": "^6.1.18",
    "babel-plugin-syntax-jsx": "^6.1.18",
    "babel-plugin-syntax-object-rest-spread": "^6.1.18",
    "babel-plugin-transform-class-properties": "^6.3.13",
    "babel-plugin-transform-decorators": "^6.1.18",
    "babel-plugin-transform-object-assign": "^6.3.13",
    "babel-plugin-transform-object-rest-spread": "^6.1.18",
    "babel-preset-es2015": "^6.1.18",
    "babel-preset-react": "^6.1.18",
    "babel-preset-stage-0": "^6.3.13",
    "babel-runtime": "^6.2.0",
    "css-loader": "^0.23.0",
    "envify": "^3.4.0",
    "eslint-plugin-react": "^3.9.0",
    "eslint-stylish": "^0.2.0",
    "grunt": "~0.4.4",
    "grunt-aws-s3": "^0.14.5",
    "grunt-browser-sync": "~2.2.0",
    "grunt-contrib-clean": "~0.6.0",
    "grunt-contrib-connect": "~0.10.1",
    "grunt-contrib-copy": "~0.8.2",
    "grunt-contrib-imagemin": "~1.0.0",
    "grunt-contrib-jade": "~0.14.1",
    "grunt-contrib-pug": "0.0.0",
    "grunt-contrib-uglify": "~0.9.1",
    "grunt-contrib-watch": "~0.6.1",
    "grunt-eslint": "~17.2.0",
    "grunt-githash": "~0.1.3",
    "grunt-newer": "^1.1.2",
    "grunt-postcss": "~0.7.1",
    "grunt-sass": "~1.1.0",
    "grunt-webpack": "~1.0.11",
    "imagemin-mozjpeg": "^5.1.0",
    "jsx-loader": "^0.13.2",
    "load-grunt-configs": "~0.4.1",
    "load-grunt-tasks": "^3.4.0",
    "node-sass": "^3.4.2",
    "postcss-loader": "^0.8.0",
    "precss": "^1.4.0",
    "react-transform-catch-errors": "^1.0.0",
    "react-transform-hmr": "^1.0.1",
    "redbox-react": "^1.2.0",
    "rimraf": "^2.5.2",
    "sass-loader": "^3.1.2",
    "style-loader": "^0.13.0",
    "svg-inline-loader": "^0.4.1",
    "svg-inline-react": "^0.3.1",
    "transform-loader": "^0.2.3",
    "webpack": "^1.12.6",
    "webpack-dev-middleware": "^1.4.0",
    "webpack-dev-server": "^1.14.0",
    "webpack-hot-middleware": "^2.6.0"
  }

i tried logging YT in the console as the first line of my render function and noticed it wasn't loaded in time. i made an action that fires on app mounting which has: 

window.onYouTubeIframeAPIReady = () => {
    dispatch(appYTReady());
}

i dont instantiate my YT.player instance until the appYTReady action has been dispatched. this added a slight delay on load time, but i had a preloader for the site so it was acceptable. something like this: 

if (this.props.app.ytReady) {
            this.state.player = new window.YT.Player(this.refs.frameWrap, {
                videoId: id,
                playerVars: opts,
                events: {
                    'onStateChange': onStateChange,
                    'onVideoEnd': onVideoEnd
                }
            });
        }


hope this helps

**Comment by kahjav** [comment]
.... I have been trying to recreate but youtube is loading every time perfectly now! I'll post again answering those questions if it happens again.

**Comment by tjallingt** [comment]
> @PhilipBrady13 
i tried logging YT in the console as the first line of my render function and noticed it wasn't loaded in time. i made an action that fires on app mounting which has:

I don't fully understand what you mean, it did load but somehow it was too late? Since `react-youtube` uses `youtube-player` to load the Youtube Iframe API not loading in time shouldn't be a problem...

> @kahjav 
.... I have been trying to recreate but youtube is loading every time perfectly now! I'll post again answering those questions if it happens again.

Both fortunate and unfortunate :laughing: 

I did notice that the both of you are using webpack in combination with a form of react hotloading. I suspect that hotloading the `react-youtube` package could somehow interfere with the Youtube Iframe API loading. Since my knowledge on hotloading is very limited and I can't test this theory I can only suggest that you somehow try to disable the hotloading and see if the problem persists (which I understand is very inconvenient :disappointed:)

**Comment by PhilipBrady13** [comment]
interesting, it did not seem like the YT api was being loaded through youtube-player, although maybe I was doing something wrong? it was not until i loaded the api myself that i started getting inconsistent behavior. could have something to do with hotloading, i do not have a ton of knowledge on the topic either though. i have since gone a different route and made my own simple YT component so can't reproduce issue from before.

**Comment by tjallingt** [comment]
@PhilipBrady13 just for clarity, when the youtube iframe api failed to load in your application; did it not load at all or did it not load "in time" or "too slow"?

**Comment by PhilipBrady13** [comment]
don't remember to be honest, i just know that i was always getting div's instead of iframes when i was not including it myself, i got inconsistent div/iframe when i started loading it myself, and i got 100% success when i started rendering after the window.onYouTubeIframeAPIReady function fired.

this leads me to believe it was either not loading in time and the component did not render an iframe afterwards, or that it did not load period. sorry i don't have an old example to test further.

**Comment by tjallingt** [comment]
@PhilipBrady13 Thanks for the explanation :smile:, you indeed need to wait for the onYouTubeIframeAPIReady when using the youtube iframe api normally but the `youtube-player` should take care of that... Anyway it's good to hear you managed to solve your problem.

**Comment by kahjav** [comment]
@tjallingt Mine was a conflicting `src="https://www.youtube.com/iframe_api"`... good call. Thanks for troubleshooting!

**Comment by tjallingt** [comment]
@kahjav can you give me some more information? What was the exact problem and (how) did you manage to fix it?
Perhaps this is something that we should create an issue for on some other package or mention in our readme...

**Comment by tjallingt** [comment]
I think we managed to "solve" most of the problems described here, therefore I will now close this issue.
If there are any further related problems I'll reopen it...
