### ISSUE TITLE
Call YouTube Iframe API `destroy()` method synchronously

### ISSUE THREAD

**Issue by tyrondis** [troybetz/react-youtube#79]
Currently, the way of styling the embedded iframe is by creating a CSS class and setting the className property of your component.

Do you think there is a way to use the React way of having a style property that you somehow attach to the embed?

**Comment by tjallingt** [comment]
Hey @tyrondis,

Although your suggestion is a good one there are some problems that prevent us from actually allowing users to pass a `style` property.

`react-youtube` initially renders as:
```jsx
<span>
  <div id={this.props.id} className={this.props.className} ref={this.refContainer} />
</span>
```
Then we call the YouTube Iframe API which replaces the `<div>` with an `<iframe>`.
After that React is unable to find the `<div>` and modify it. This means that the properties `id` and `className` won't automatically update after the initial render.
To fix this `react-youtube` checks whether the `id` or `className` props change and uses `setAttribute` to change their values "manually".

**Note:** this wouldn't happen if the `<div>` was the root element of the `react-youtube` component. Apparently React is capable of updating the root element even when it is replaced with another element. However this causes errors when React tries to remove the element and realises that it can't find the original element anymore. The YouTube Iframe API does allow you to reset the element it was instantiated on but this doesn't happen fast enough (same tick) because of the use of Promises.

Now on to the answer to your question; Because we have to "manually" update properties on the element we'd need to parse the css object that is handed down to us by React. Sadly React-dom does not have a method for parsing css objects to strings that we could use and therefore we can't implement a `style` property for the time being.

Additional note: Now that I think about it; it's pretty strange that React would update the replaced element as long as it is the root of the component. perhaps it is wise to look into that, if that is an actual feature of React that we can rely on it might be worth figuring out whether or not we can manage to call `destroy()` on the YouTube Iframe API synchronously. That'd allow us to remove the `<span>` and then we could add stuff like a `style` property.
