### ISSUE TITLE
Allow a pass-through "style" prop

### ISSUE THREAD

**Issue by brendonlamb** [troybetz/react-youtube#94]
I'd like to apply styles to the iFrame element (and I suppose the wrapping span could be helpful too)- is that something you could add?

**Comment by tjallingt** [comment]
Hey @brendonlamb, applying styles to the `<iframe>` is possible and we should probably add it, however since we technically render a `<div>` that gets replaced by the YouTube IFrame API we rely on somewhat quirky behaviour from react (to update properties on elements it did not render directly).

Feel free to make a pull request that implements this behaviour or let me know if that is not possible 👍 

If anyone has some other thoughts on this 'd like to hear 😃

**Comment by brendonlamb** [comment]
Thanks- sorry i didn't do a PR, I'm a bum. :D

I ended up doing this:


    event.target.a.style.position = 'absolute';
    event.target.a.style.top = '-50%';
    event.target.a.style.left = '-50%';
    event.target.a.style.height = '200%';
    event.target.a.style.width = '200%';
    event.target.a.style.pointerEvents = 'none';


(Don't ask about the crazy styling lol) - I guess it's a work-around but it felt more "reacty" because you can use this.state.player.a.style - which isn't too different from building a const "style" like we do for other things...
And it turns out I only needed to set the styles once (initially) so once it's done it works out just fine. Cool background right? https://www.riders-share.com/

**Comment by goto-bus-stop** [comment]
Also for future reference: most styles can be implemented using a wrapper div, and setting the iframe size to fill the entire wrapper:

```js
const opts = {
  // Fill the wrapper div:
  width: '100%',
  height: '100%',
  // Other options:
  playerVars: { /* etc */ },
};

const style = {
  position: 'absolute',
  top: '-50%',
  left: '-50%',
  height: '200%',
  width: '200%',
  pointerEvents: 'none',
};

<div style={style}>
  <YouTube videoId="myVideo" opts={opts} />
</div>
```
